# Site settings
title: ""
description: >
  Alexandra's personal website

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://prosecco75.github.io" # the base hostname & protocol for your site

author:
  fullname: Alexandra Bringazen
  # googleplus: https://www.google.com/+MotaquillahMaddane
  github: prosecco75
  twitter: prosecco75
  # disqus: your_disqus_username

# google_analytics: 'UA-XXXXXXXX-X'

# Build settings
markdown: kramdown
